apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps/
    ## todo: move to secret auth_token
    repoURL: https://argobot:glpat-iX9M_JkgC1ivC8FTixoY@gitlab.dev.clover.tech/devops/begames-eu/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true