apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-apps
  namespace: system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: system
  project: system-proj
  source:
    path: apps/system
    repoURL: https://github.com/fojman/my-argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true