apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: system
spec:
  project: system-proj
  source:
    repoURL: 'https://kubernetes-sigs.github.io/external-dns/'
    targetRevision: 1.12.0
    chart: external-dns
    helm:
      values:
        aws:
          apiRetries: 3
          batchChangeSize: 10
          region: eu-central-1
        domainFilters:
          - begames.tech
        forceTxtOwnerId: false
        interval: 1m
        logFormat: json
        logLevel: info
        metrics:
          enabled: false
          serviceMonitor:
            enabled: false
        policy: upsert-only
        provider: aws
        rbac:
          apiVersion: v1
          clusterRole: true
          create: true
        registry: txt
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::637594911457:role/ExternalDNSControllerRole
          create: true
        txtOwnerId: "begames-eu-eks"     
#      valueFiles:
#        - values.yaml
#      parameters:
#        - name: param
#          value: "value"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true